### ISSUE TITLE
Direct URL

### ISSUE THREAD

**Issue by ianobre** [luicaps/infraero-wsdl-restapi#2]
Olá, você poderia mandar um exemplo da chamada direta da API, não entendi onde entra o /api/.

**Comment by cslaviero** [comment]
@ianobre , depois de rodar o apps.js , você pode usar localhost:3000/api/<comando>?<argumentos>

**Comment by ianobre** [comment]
Na real sou bem juvenil com node.js, hehehe estou tentando instalar para pegar as urls de acesso para criar um serviço via Laravel. Por isto perguntei das urls diretas do serviço.

Obrigado por responder.

**Comment by cslaviero** [comment]
Ih, não foi exatamente essa minha resposta :P , depois de /api/ vai o comando, depois  "?" e depois os argumentos, como nos exemplos do readme. 

Mas vou passar uma dica interessante: a infraero está em vias de deprecar esse web service. O novo app deles já usa um acesso diferente, que joga respostas em json (o que facilita horrores). Existem uns decompilers para android por aí, e sites que te permitem baixar o apk . Pra evitar problemas não divullgarei links aqui, mas não é difícil encontrar :)

**Comment by ianobre** [comment]
hummmm show de bola, verei isto então. JSON seria perfeito. Ainda bem q ninguém conhece SSL lá, kkkkkkkkk

**Comment by ianobre** [comment]
tô total noob nesta parada, acabei de fazer o q vc comentou, mas no apk publicado dia 30 de março de 2016 usa o mesmo serviço

**Comment by luicaps** [comment]
@ianobre não é tão simples mesmo usar o serviço deles, apanhei um bocado pra entender como organizar as chamadas.

Dentro da função da linha 38, você pode colocar 
`console.log(client);`
Quando rodar, o print na tela vai mostrar todo o xml do serviço da infraero "quase organizado" como JSON. Disso você consegue ver quais são os possíveis comandos que podem ser executados dentro da função na linha 14.

Eu não consigo rodar ele agora, mas se quiser, joga esse print aqui que eu dou uma olhada.

**Comment by luicaps** [comment]
Já que você já optou por PHP, talvez seja mais fácil tentar usar o SOAP por lá

http://php.net/manual/en/class.soapclient.php

a url de acesso da infraero é

http://voos.infraero.gov.br/wsvoosmobile/ConsultaVoos.svc?singleWsdl

**Comment by ianobre** [comment]
Hehehehe, @luicaps foi exatamente o q eu fiz depois dos seus comentários de ontem do @cslaviero . Deu certinho, 4 linhas de código já resolvi a questão, agora já posso fazer uma estimativa de prazos para a demanda. Muito obrigado pela ajuda galera. Vou estudar um pouco de node que está valendo :-)
